apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  MYSQL_USER: dXNlcmFwcGxp  # userappli encodé en base64
  MYSQL_PASSWORD: dXNlcmFwcGxp  # userappli encodé en base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword encodé en base64